function Hd = bandpass_filter_75e3
%BANDPASS_FILTER_75E3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 09-Mar-2015 15:12:27

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 250000;  % Sampling Frequency

Fstop1 = 60000;           % First Stopband Frequency
Fpass1 = 70000;           % First Passband Frequency
Fpass2 = 80000;           % Second Passband Frequency
Fstop2 = 90000;           % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
