function Hd = bandpass_butterworth_filter_25e3
%BANDPASS_BUTTERWORTH_FILTER_25E3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 09-Mar-2015 15:40:36

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 250000;  % Sampling Frequency

Fstop1 = 10000;       % First Stopband Frequency
Fpass1 = 20000;       % First Passband Frequency
Fpass2 = 30000;       % Second Passband Frequency
Fstop2 = 40000;       % Second Stopband Frequency
Astop1 = 40;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 40;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
